spring:
  profiles:
    active: dev

app:
  jwt:
    secret: "DigitalDetoxSuperSecretKeyForJWT2024ChangeInProduction!!"
    expiration-ms: 86400000

# =========================
# DEV (H2)
# =========================
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:file:./data/digitaldetox;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  simulation:
    enabled: true
    schedule-cron: "0 */5 * * * *"

logging:
  level:
    com.digitaldetox: DEBUG
    org.springframework.security: INFO

server:
  port: 8080

# =========================
# PROD (PostgreSQL - Railway)
# =========================
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # puoi mettere validate in futuro
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  simulation:
    enabled: false

logging:
  level:
    com.digitaldetox: INFO

server:
  port: ${PORT:8080}